/*
 * This file is generated by jOOQ.
 */
package com.tll.mcorpus.db.udt.records;


import com.tll.mcorpus.db.enums.JwtStatus;
import com.tll.mcorpus.db.udt.JwtStatusMcuserRole;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UDTRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JwtStatusMcuserRoleRecord extends UDTRecordImpl<JwtStatusMcuserRoleRecord> implements Record2<JwtStatus, String> {

    private static final long serialVersionUID = -2137393484;

    /**
     * Setter for <code>public.jwt_status_mcuser_role.jwt_status</code>.
     */
    public void setJwtStatus(JwtStatus value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.jwt_status_mcuser_role.jwt_status</code>.
     */
    public JwtStatus getJwtStatus() {
        return (JwtStatus) get(0);
    }

    /**
     * Setter for <code>public.jwt_status_mcuser_role.roles</code>.
     */
    public void setRoles(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.jwt_status_mcuser_role.roles</code>.
     */
    public String getRoles() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<JwtStatus, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<JwtStatus, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JwtStatus> field1() {
        return JwtStatusMcuserRole.JWT_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JwtStatusMcuserRole.ROLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JwtStatus component1() {
        return getJwtStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRoles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JwtStatus value1() {
        return getJwtStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRoles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JwtStatusMcuserRoleRecord value1(JwtStatus value) {
        setJwtStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JwtStatusMcuserRoleRecord value2(String value) {
        setRoles(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JwtStatusMcuserRoleRecord values(JwtStatus value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JwtStatusMcuserRoleRecord
     */
    public JwtStatusMcuserRoleRecord() {
        super(JwtStatusMcuserRole.JWT_STATUS_MCUSER_ROLE);
    }

    /**
     * Create a detached, initialised JwtStatusMcuserRoleRecord
     */
    public JwtStatusMcuserRoleRecord(JwtStatus jwtStatus, String roles) {
        super(JwtStatusMcuserRole.JWT_STATUS_MCUSER_ROLE);

        set(0, jwtStatus);
        set(1, roles);
    }
}
