version: 0.2

env:
  parameter-store:
    MCORPUS_DB_URL: mcorpusDbUrl
    MCORPUS_TEST_DB_URL: mcorpusTestDbUrl

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean test
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - appspec-ec2.yml
    - mcorpus-gql/target/aws/appStart.sh
    - mcorpus-gql/target/aws/appStop.sh
    - mcorpus-gql/target/aws/appValidate.sh
    - mcorpus-gql/target/aws/run.sh
    - mcorpus-gql/target/log4j2-aws.xml
    - mcorpus-gql/target/mcorpus-gql-server.jar
    - mcorpus-gql/target/disruptor-3.4.2.jar
    - mcorpus-gql/target/log4j-api-2.11.2.jar
    - mcorpus-gql/target/log4j-core-2.11.2.jar
    - mcorpus-gql/target/log4j-slf4j-impl-2.11.2.jar
  discard-paths: yes
