/*
 * This file is generated by jOOQ.
*/
package com.tll.mcorpus.db.tables.records;


import com.tll.mcorpus.db.enums.McuserAuditType;
import com.tll.mcorpus.db.tables.McuserAudit;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class McuserAuditRecord extends UpdatableRecordImpl<McuserAuditRecord> implements Record9<UUID, Timestamp, McuserAuditType, String, String, String, String, String, String> {

    private static final long serialVersionUID = -922126993;

    /**
     * Setter for <code>public.mcuser_audit.uid</code>.
     */
    public void setUid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mcuser_audit.uid</code>.
     */
    public UUID getUid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.mcuser_audit.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mcuser_audit.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.mcuser_audit.type</code>.
     */
    public void setType(McuserAuditType value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mcuser_audit.type</code>.
     */
    public McuserAuditType getType() {
        return (McuserAuditType) get(2);
    }

    /**
     * Setter for <code>public.mcuser_audit.web_session_id</code>.
     */
    public void setWebSessionId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mcuser_audit.web_session_id</code>.
     */
    public String getWebSessionId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mcuser_audit.remote_addr</code>.
     */
    public void setRemoteAddr(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mcuser_audit.remote_addr</code>.
     */
    public String getRemoteAddr() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mcuser_audit.http_host</code>.
     */
    public void setHttpHost(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mcuser_audit.http_host</code>.
     */
    public String getHttpHost() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mcuser_audit.http_origin</code>.
     */
    public void setHttpOrigin(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mcuser_audit.http_origin</code>.
     */
    public String getHttpOrigin() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mcuser_audit.http_referer</code>.
     */
    public void setHttpReferer(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mcuser_audit.http_referer</code>.
     */
    public String getHttpReferer() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mcuser_audit.http_forwarded</code>.
     */
    public void setHttpForwarded(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mcuser_audit.http_forwarded</code>.
     */
    public String getHttpForwarded() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Timestamp, McuserAuditType> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UUID, Timestamp, McuserAuditType, String, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UUID, Timestamp, McuserAuditType, String, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return McuserAudit.MCUSER_AUDIT.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return McuserAudit.MCUSER_AUDIT.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<McuserAuditType> field3() {
        return McuserAudit.MCUSER_AUDIT.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return McuserAudit.MCUSER_AUDIT.WEB_SESSION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return McuserAudit.MCUSER_AUDIT.REMOTE_ADDR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return McuserAudit.MCUSER_AUDIT.HTTP_HOST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return McuserAudit.MCUSER_AUDIT.HTTP_ORIGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return McuserAudit.MCUSER_AUDIT.HTTP_REFERER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return McuserAudit.MCUSER_AUDIT.HTTP_FORWARDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public McuserAuditType component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getWebSessionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getRemoteAddr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getHttpHost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getHttpOrigin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getHttpReferer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getHttpForwarded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public McuserAuditType value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getWebSessionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRemoteAddr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getHttpHost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getHttpOrigin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getHttpReferer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getHttpForwarded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public McuserAuditRecord value1(UUID value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public McuserAuditRecord value2(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public McuserAuditRecord value3(McuserAuditType value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public McuserAuditRecord value4(String value) {
        setWebSessionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public McuserAuditRecord value5(String value) {
        setRemoteAddr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public McuserAuditRecord value6(String value) {
        setHttpHost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public McuserAuditRecord value7(String value) {
        setHttpOrigin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public McuserAuditRecord value8(String value) {
        setHttpReferer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public McuserAuditRecord value9(String value) {
        setHttpForwarded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public McuserAuditRecord values(UUID value1, Timestamp value2, McuserAuditType value3, String value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached McuserAuditRecord
     */
    public McuserAuditRecord() {
        super(McuserAudit.MCUSER_AUDIT);
    }

    /**
     * Create a detached, initialised McuserAuditRecord
     */
    public McuserAuditRecord(UUID uid, Timestamp created, McuserAuditType type, String webSessionId, String remoteAddr, String httpHost, String httpOrigin, String httpReferer, String httpForwarded) {
        super(McuserAudit.MCUSER_AUDIT);

        set(0, uid);
        set(1, created);
        set(2, type);
        set(3, webSessionId);
        set(4, remoteAddr);
        set(5, httpHost);
        set(6, httpOrigin);
        set(7, httpReferer);
        set(8, httpForwarded);
    }
}
