/*
 * This file is generated by jOOQ.
 */
package com.tll.mcorpus.db.udt.pojos;


import com.tll.mcorpus.db.enums.JwtIdStatus;
import com.tll.mcorpus.db.enums.McuserAuditType;
import com.tll.mcorpus.db.enums.McuserStatus;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JwtMcuserStatus implements Serializable {

    private static final long serialVersionUID = -1667539529;

    private final McuserAuditType mcuserAuditRecordType;
    private final UUID            jwtId;
    private final JwtIdStatus     jwtIdStatus;
    private final Timestamp       loginExpiration;
    private final UUID            uid;
    private final McuserStatus    mcuserStatus;

    public JwtMcuserStatus(JwtMcuserStatus value) {
        this.mcuserAuditRecordType = value.mcuserAuditRecordType;
        this.jwtId = value.jwtId;
        this.jwtIdStatus = value.jwtIdStatus;
        this.loginExpiration = value.loginExpiration;
        this.uid = value.uid;
        this.mcuserStatus = value.mcuserStatus;
    }

    public JwtMcuserStatus(
        McuserAuditType mcuserAuditRecordType,
        UUID            jwtId,
        JwtIdStatus     jwtIdStatus,
        Timestamp       loginExpiration,
        UUID            uid,
        McuserStatus    mcuserStatus
    ) {
        this.mcuserAuditRecordType = mcuserAuditRecordType;
        this.jwtId = jwtId;
        this.jwtIdStatus = jwtIdStatus;
        this.loginExpiration = loginExpiration;
        this.uid = uid;
        this.mcuserStatus = mcuserStatus;
    }

    public McuserAuditType getMcuserAuditRecordType() {
        return this.mcuserAuditRecordType;
    }

    public UUID getJwtId() {
        return this.jwtId;
    }

    public JwtIdStatus getJwtIdStatus() {
        return this.jwtIdStatus;
    }

    public Timestamp getLoginExpiration() {
        return this.loginExpiration;
    }

    public UUID getUid() {
        return this.uid;
    }

    public McuserStatus getMcuserStatus() {
        return this.mcuserStatus;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JwtMcuserStatus (");

        sb.append(mcuserAuditRecordType);
        sb.append(", ").append(jwtId);
        sb.append(", ").append(jwtIdStatus);
        sb.append(", ").append(loginExpiration);
        sb.append(", ").append(uid);
        sb.append(", ").append(mcuserStatus);

        sb.append(")");
        return sb.toString();
    }
}
