/*
 * This file is generated by jOOQ.
 */
package com.tll.mcorpus.db.udt.pojos;


import com.tll.mcorpus.db.tables.pojos.Mcuser;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class McuserAndRoles implements Serializable {

    private static final long serialVersionUID = -126677509;

    private final Mcuser mcuser;
    private final String roles;

    public McuserAndRoles(McuserAndRoles value) {
        this.mcuser = value.mcuser;
        this.roles = value.roles;
    }

    public McuserAndRoles(
        Mcuser mcuser,
        String roles
    ) {
        this.mcuser = mcuser;
        this.roles = roles;
    }

    public Mcuser getMcuser() {
        return this.mcuser;
    }

    public String getRoles() {
        return this.roles;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("McuserAndRoles (");

        sb.append(mcuser);
        sb.append(", ").append(roles);

        sb.append(")");
        return sb.toString();
    }
}
