/*
 * This file is generated by jOOQ.
 */
package com.tll.mcorpus.db.udt.pojos;


import com.tll.mcorpus.db.enums.Location;

import java.io.Serializable;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mref implements Serializable {

    private static final long serialVersionUID = 355660398;

    private final UUID     mid;
    private final String   empId;
    private final Location location;

    public Mref(Mref value) {
        this.mid = value.mid;
        this.empId = value.empId;
        this.location = value.location;
    }

    public Mref(
        UUID     mid,
        String   empId,
        Location location
    ) {
        this.mid = mid;
        this.empId = empId;
        this.location = location;
    }

    public UUID getMid() {
        return this.mid;
    }

    public String getEmpId() {
        return this.empId;
    }

    public Location getLocation() {
        return this.location;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Mref (");

        sb.append(mid);
        sb.append(", ").append(empId);
        sb.append(", ").append(location);

        sb.append(")");
        return sb.toString();
    }
}
