/*
 * This file is generated by jOOQ.
 */
package com.tll.mcorpus.db.routines;


import com.tll.mcorpus.db.Public;
import com.tll.mcorpus.db.udt.records.JwtStatusMcuserRoleRecord;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetJwtStatus extends AbstractRoutine<JwtStatusMcuserRoleRecord> {

    private static final long serialVersionUID = 82691891;

    /**
     * The parameter <code>public.get_jwt_status.RETURN_VALUE</code>.
     */
    public static final Parameter<JwtStatusMcuserRoleRecord> RETURN_VALUE = createParameter("RETURN_VALUE", com.tll.mcorpus.db.udt.JwtStatusMcuserRole.JWT_STATUS_MCUSER_ROLE.getDataType(), false, false);

    /**
     * The parameter <code>public.get_jwt_status.jwt_id</code>.
     */
    public static final Parameter<UUID> JWT_ID = createParameter("jwt_id", org.jooq.impl.SQLDataType.UUID, false, false);

    /**
     * Create a new routine call instance
     */
    public GetJwtStatus() {
        super("get_jwt_status", Public.PUBLIC, com.tll.mcorpus.db.udt.JwtStatusMcuserRole.JWT_STATUS_MCUSER_ROLE.getDataType());

        setReturnParameter(RETURN_VALUE);
        addInParameter(JWT_ID);
    }

    /**
     * Set the <code>jwt_id</code> parameter IN value to the routine
     */
    public void setJwtId(UUID value) {
        setValue(JWT_ID, value);
    }

    /**
     * Set the <code>jwt_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setJwtId(Field<UUID> field) {
        setField(JWT_ID, field);
    }
}
