/*
 * This file is generated by jOOQ.
*/
package com.tll.mcorpus.db.routines;


import com.tll.mcorpus.db.Public;
import com.tll.mcorpus.db.tables.records.McuserRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Login extends AbstractRoutine<McuserRecord> {

    private static final long serialVersionUID = 814001390;

    /**
     * The parameter <code>public.login.RETURN_VALUE</code>.
     */
    public static final Parameter<McuserRecord> RETURN_VALUE = createParameter("RETURN_VALUE", com.tll.mcorpus.db.tables.Mcuser.MCUSER.getDataType(), false, false);

    /**
     * The parameter <code>public.login.user_username</code>.
     */
    public static final Parameter<String> USER_USERNAME = createParameter("user_username", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.login.user_password</code>.
     */
    public static final Parameter<String> USER_PASSWORD = createParameter("user_password", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.login.user_session_id</code>.
     */
    public static final Parameter<String> USER_SESSION_ID = createParameter("user_session_id", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.login.user_ip</code>.
     */
    public static final Parameter<String> USER_IP = createParameter("user_ip", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.login.user_host</code>.
     */
    public static final Parameter<String> USER_HOST = createParameter("user_host", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.login.user_origin</code>.
     */
    public static final Parameter<String> USER_ORIGIN = createParameter("user_origin", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.login.user_referer</code>.
     */
    public static final Parameter<String> USER_REFERER = createParameter("user_referer", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.login.user_forwarded</code>.
     */
    public static final Parameter<String> USER_FORWARDED = createParameter("user_forwarded", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public Login() {
        super("login", Public.PUBLIC, com.tll.mcorpus.db.tables.Mcuser.MCUSER.getDataType());

        setReturnParameter(RETURN_VALUE);
        addInParameter(USER_USERNAME);
        addInParameter(USER_PASSWORD);
        addInParameter(USER_SESSION_ID);
        addInParameter(USER_IP);
        addInParameter(USER_HOST);
        addInParameter(USER_ORIGIN);
        addInParameter(USER_REFERER);
        addInParameter(USER_FORWARDED);
    }

    /**
     * Set the <code>user_username</code> parameter IN value to the routine
     */
    public void setUserUsername(String value) {
        setValue(USER_USERNAME, value);
    }

    /**
     * Set the <code>user_username</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setUserUsername(Field<String> field) {
        setField(USER_USERNAME, field);
    }

    /**
     * Set the <code>user_password</code> parameter IN value to the routine
     */
    public void setUserPassword(String value) {
        setValue(USER_PASSWORD, value);
    }

    /**
     * Set the <code>user_password</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setUserPassword(Field<String> field) {
        setField(USER_PASSWORD, field);
    }

    /**
     * Set the <code>user_session_id</code> parameter IN value to the routine
     */
    public void setUserSessionId(String value) {
        setValue(USER_SESSION_ID, value);
    }

    /**
     * Set the <code>user_session_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setUserSessionId(Field<String> field) {
        setField(USER_SESSION_ID, field);
    }

    /**
     * Set the <code>user_ip</code> parameter IN value to the routine
     */
    public void setUserIp(String value) {
        setValue(USER_IP, value);
    }

    /**
     * Set the <code>user_ip</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setUserIp(Field<String> field) {
        setField(USER_IP, field);
    }

    /**
     * Set the <code>user_host</code> parameter IN value to the routine
     */
    public void setUserHost(String value) {
        setValue(USER_HOST, value);
    }

    /**
     * Set the <code>user_host</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setUserHost(Field<String> field) {
        setField(USER_HOST, field);
    }

    /**
     * Set the <code>user_origin</code> parameter IN value to the routine
     */
    public void setUserOrigin(String value) {
        setValue(USER_ORIGIN, value);
    }

    /**
     * Set the <code>user_origin</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setUserOrigin(Field<String> field) {
        setField(USER_ORIGIN, field);
    }

    /**
     * Set the <code>user_referer</code> parameter IN value to the routine
     */
    public void setUserReferer(String value) {
        setValue(USER_REFERER, value);
    }

    /**
     * Set the <code>user_referer</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setUserReferer(Field<String> field) {
        setField(USER_REFERER, field);
    }

    /**
     * Set the <code>user_forwarded</code> parameter IN value to the routine
     */
    public void setUserForwarded(String value) {
        setValue(USER_FORWARDED, value);
    }

    /**
     * Set the <code>user_forwarded</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setUserForwarded(Field<String> field) {
        setField(USER_FORWARDED, field);
    }
}
