/*
 * This file is generated by jOOQ.
*/
package com.tll.mcorpus.db.routines;


import com.tll.mcorpus.db.Public;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Logout extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1838217296;

    /**
     * The parameter <code>public.logout.user_uid</code>.
     */
    public static final Parameter<UUID> USER_UID = createParameter("user_uid", org.jooq.impl.SQLDataType.UUID, false, false);

    /**
     * The parameter <code>public.logout.user_session_id</code>.
     */
    public static final Parameter<String> USER_SESSION_ID = createParameter("user_session_id", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public Logout() {
        super("logout", Public.PUBLIC);

        addInParameter(USER_UID);
        addInParameter(USER_SESSION_ID);
    }

    /**
     * Set the <code>user_uid</code> parameter IN value to the routine
     */
    public void setUserUid(UUID value) {
        setValue(USER_UID, value);
    }

    /**
     * Set the <code>user_session_id</code> parameter IN value to the routine
     */
    public void setUserSessionId(String value) {
        setValue(USER_SESSION_ID, value);
    }
}
