/*
 * This file is generated by jOOQ.
*/
package com.tll.mcorpus.db.routines;


import com.tll.mcorpus.db.Public;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberLogout extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 770932281;

    /**
     * The parameter <code>public.member_logout.mid</code>.
     */
    public static final Parameter<UUID> MID = createParameter("mid", org.jooq.impl.SQLDataType.UUID, false, false);

    /**
     * The parameter <code>public.member_logout.member_web_session_id</code>.
     */
    public static final Parameter<String> MEMBER_WEB_SESSION_ID = createParameter("member_web_session_id", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public MemberLogout() {
        super("member_logout", Public.PUBLIC);

        addInParameter(MID);
        addInParameter(MEMBER_WEB_SESSION_ID);
    }

    /**
     * Set the <code>mid</code> parameter IN value to the routine
     */
    public void setMid(UUID value) {
        setValue(MID, value);
    }

    /**
     * Set the <code>member_web_session_id</code> parameter IN value to the routine
     */
    public void setMemberWebSessionId(String value) {
        setValue(MEMBER_WEB_SESSION_ID, value);
    }
}
