/*
 * This file is generated by jOOQ.
 */
package com.tll.mcorpus.db.routines;


import com.tll.mcorpus.db.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PassHash extends AbstractRoutine<String> {

    private static final long serialVersionUID = -1196326879;

    /**
     * The parameter <code>public.pass_hash.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.pass_hash.pswd</code>.
     */
    public static final Parameter<String> PSWD = Internal.createParameter("pswd", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public PassHash() {
        super("pass_hash", Public.PUBLIC, org.jooq.impl.SQLDataType.CLOB);

        setReturnParameter(RETURN_VALUE);
        addInParameter(PSWD);
    }

    /**
     * Set the <code>pswd</code> parameter IN value to the routine
     */
    public void setPswd(String value) {
        setValue(PSWD, value);
    }

    /**
     * Set the <code>pswd</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPswd(Field<String> field) {
        setField(PSWD, field);
    }
}
