/*
 * This file is generated by jOOQ.
 */
package com.tll.mcorpus.db.udt;


import com.tll.mcorpus.db.Public;
import com.tll.mcorpus.db.tables.records.McuserRecord;
import com.tll.mcorpus.db.udt.records.McuserAndRolesRecord;

import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.UDTField;
import org.jooq.impl.UDTImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class McuserAndRoles extends UDTImpl<McuserAndRolesRecord> {

    private static final long serialVersionUID = -2042681714;

    /**
     * The reference instance of <code>public.mcuser_and_roles</code>
     */
    public static final McuserAndRoles MCUSER_AND_ROLES = new McuserAndRoles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<McuserAndRolesRecord> getRecordType() {
        return McuserAndRolesRecord.class;
    }

    /**
     * The attribute <code>public.mcuser_and_roles.mcuser</code>.
     */
    public static final UDTField<McuserAndRolesRecord, McuserRecord> MCUSER = createField("mcuser", com.tll.mcorpus.db.tables.Mcuser.MCUSER.getDataType(), MCUSER_AND_ROLES, "");

    /**
     * The attribute <code>public.mcuser_and_roles.roles</code>.
     */
    public static final UDTField<McuserAndRolesRecord, String> ROLES = createField("roles", org.jooq.impl.SQLDataType.CLOB, MCUSER_AND_ROLES, "");

    /**
     * No further instances allowed
     */
    private McuserAndRoles() {
        super("mcuser_and_roles", null, null, false);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }
}
