/*
 * This file is generated by jOOQ.
 */
package com.tll.mcorpus.db;


import com.tll.mcorpus.db.tables.McuserAudit;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

		// -------------------------------------------------------------------------
		// INDEX definitions
		// -------------------------------------------------------------------------

		public static final Index MCUSER_AUDIT__JWT_ID = Internal.createIndex(DSL.name("mcuser_audit__jwt_id"), McuserAudit.MCUSER_AUDIT, new OrderField[] { McuserAudit.MCUSER_AUDIT.JWT_ID }, false);
}
