/*
 * This file is generated by jOOQ.
 */
package com.tll.mcorpus.db;


import com.tll.mcorpus.db.tables.Maddress;
import com.tll.mcorpus.db.tables.Mauth;
import com.tll.mcorpus.db.tables.Mbenefits;
import com.tll.mcorpus.db.tables.Mcuser;
import com.tll.mcorpus.db.tables.McuserAudit;
import com.tll.mcorpus.db.tables.Member;
import com.tll.mcorpus.db.tables.MemberAudit;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.maddress</code>.
     */
    public static final Maddress MADDRESS = Maddress.MADDRESS;

    /**
     * The table <code>public.mauth</code>.
     */
    public static final Mauth MAUTH = Mauth.MAUTH;

    /**
     * The table <code>public.mbenefits</code>.
     */
    public static final Mbenefits MBENEFITS = Mbenefits.MBENEFITS;

    /**
     * The table <code>public.mcuser</code>.
     */
    public static final Mcuser MCUSER = Mcuser.MCUSER;

    /**
     * The table <code>public.mcuser_audit</code>.
     */
    public static final McuserAudit MCUSER_AUDIT = McuserAudit.MCUSER_AUDIT;

    /**
     * The table <code>public.member</code>.
     */
    public static final Member MEMBER = Member.MEMBER;

    /**
     * The table <code>public.member_audit</code>.
     */
    public static final MemberAudit MEMBER_AUDIT = MemberAudit.MEMBER_AUDIT;
}
