/*
 * This file is generated by jOOQ.
*/
package com.tll.mcorpus.db;


import com.tll.mcorpus.db.udt.JwtAndMcuserStatus;
import com.tll.mcorpus.db.udt.Mref;

import javax.annotation.Generated;


/**
 * Convenience access to all UDTs in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UDTs {

    /**
     * The type <code>public.jwt_and_mcuser_status</code>
     */
    public static JwtAndMcuserStatus JWT_AND_MCUSER_STATUS = com.tll.mcorpus.db.udt.JwtAndMcuserStatus.JWT_AND_MCUSER_STATUS;

    /**
     * The type <code>public.mref</code>
     */
    public static Mref MREF = com.tll.mcorpus.db.udt.Mref.MREF;
}
