/*
 * This file is generated by jOOQ.
 */
package com.tll.mcorpus.db.tables;


import com.tll.mcorpus.db.Indexes;
import com.tll.mcorpus.db.Keys;
import com.tll.mcorpus.db.Public;
import com.tll.mcorpus.db.enums.Beli;
import com.tll.mcorpus.db.tables.records.MbenefitsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mbenefits extends TableImpl<MbenefitsRecord> {

    private static final long serialVersionUID = 433644284;

    /**
     * The reference instance of <code>public.mbenefits</code>
     */
    public static final Mbenefits MBENEFITS = new Mbenefits();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbenefitsRecord> getRecordType() {
        return MbenefitsRecord.class;
    }

    /**
     * The column <code>public.mbenefits.mid</code>.
     */
    public final TableField<MbenefitsRecord, UUID> MID = createField(DSL.name("mid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.mbenefits.modified</code>.
     */
    public final TableField<MbenefitsRecord, OffsetDateTime> MODIFIED = createField(DSL.name("modified"), org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mbenefits.foreign_adrs_flag</code>.
     */
    public final TableField<MbenefitsRecord, String> FOREIGN_ADRS_FLAG = createField(DSL.name("foreign_adrs_flag"), org.jooq.impl.SQLDataType.CHAR(1), this, "");

    /**
     * The column <code>public.mbenefits.beli</code>.
     */
    public final TableField<MbenefitsRecord, Beli> BELI = createField(DSL.name("beli"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false).asEnumDataType(com.tll.mcorpus.db.enums.Beli.class), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<MbenefitsRecord, Object> MCB = createField(DSL.name("mcb"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"money\"").nullable(false), this, "");

    /**
     * The column <code>public.mbenefits.med_plan_code</code>.
     */
    public final TableField<MbenefitsRecord, String> MED_PLAN_CODE = createField(DSL.name("med_plan_code"), org.jooq.impl.SQLDataType.CHAR(2), this, "");

    /**
     * The column <code>public.mbenefits.med_opt_out</code>.
     */
    public final TableField<MbenefitsRecord, String> MED_OPT_OUT = createField(DSL.name("med_opt_out"), org.jooq.impl.SQLDataType.CHAR(2), this, "");

    /**
     * The column <code>public.mbenefits.den_plan_code</code>.
     */
    public final TableField<MbenefitsRecord, String> DEN_PLAN_CODE = createField(DSL.name("den_plan_code"), org.jooq.impl.SQLDataType.CHAR(2), this, "");

    /**
     * The column <code>public.mbenefits.den_opt_out</code>.
     */
    public final TableField<MbenefitsRecord, String> DEN_OPT_OUT = createField(DSL.name("den_opt_out"), org.jooq.impl.SQLDataType.CHAR(2), this, "");

    /**
     * The column <code>public.mbenefits.vis_plan_code</code>.
     */
    public final TableField<MbenefitsRecord, String> VIS_PLAN_CODE = createField(DSL.name("vis_plan_code"), org.jooq.impl.SQLDataType.CHAR(2), this, "");

    /**
     * The column <code>public.mbenefits.vis_opt_out</code>.
     */
    public final TableField<MbenefitsRecord, String> VIS_OPT_OUT = createField(DSL.name("vis_opt_out"), org.jooq.impl.SQLDataType.CHAR(2), this, "");

    /**
     * The column <code>public.mbenefits.leg_plan_code</code>.
     */
    public final TableField<MbenefitsRecord, String> LEG_PLAN_CODE = createField(DSL.name("leg_plan_code"), org.jooq.impl.SQLDataType.CHAR(2), this, "");

    /**
     * The column <code>public.mbenefits.leg_opt_out</code>.
     */
    public final TableField<MbenefitsRecord, String> LEG_OPT_OUT = createField(DSL.name("leg_opt_out"), org.jooq.impl.SQLDataType.CHAR(2), this, "");

    /**
     * Create a <code>public.mbenefits</code> table reference
     */
    public Mbenefits() {
        this(DSL.name("mbenefits"), null);
    }

    /**
     * Create an aliased <code>public.mbenefits</code> table reference
     */
    public Mbenefits(String alias) {
        this(DSL.name(alias), MBENEFITS);
    }

    /**
     * Create an aliased <code>public.mbenefits</code> table reference
     */
    public Mbenefits(Name alias) {
        this(alias, MBENEFITS);
    }

    private Mbenefits(Name alias, Table<MbenefitsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Mbenefits(Name alias, Table<MbenefitsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Mbenefits(Table<O> child, ForeignKey<O, MbenefitsRecord> key) {
        super(child, key, MBENEFITS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MBENEFITS_PKEY);
    }

    @Override
    public UniqueKey<MbenefitsRecord> getPrimaryKey() {
        return Keys.MBENEFITS_PKEY;
    }

    @Override
    public List<UniqueKey<MbenefitsRecord>> getKeys() {
        return Arrays.<UniqueKey<MbenefitsRecord>>asList(Keys.MBENEFITS_PKEY);
    }

    @Override
    public List<ForeignKey<MbenefitsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MbenefitsRecord, ?>>asList(Keys.MBENEFITS__MBENEFITS_MID_FKEY);
    }

    public Member member() {
        return new Member(this, Keys.MBENEFITS__MBENEFITS_MID_FKEY);
    }

    @Override
    public Mbenefits as(String alias) {
        return new Mbenefits(DSL.name(alias), this);
    }

    @Override
    public Mbenefits as(Name alias) {
        return new Mbenefits(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Mbenefits rename(String name) {
        return new Mbenefits(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Mbenefits rename(Name name) {
        return new Mbenefits(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<UUID, OffsetDateTime, String, Beli, Object, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
