/*
 * This file is generated by jOOQ.
 */
package com.tll.mcorpus.db.tables.pojos;


import com.tll.mcorpus.db.enums.JwtIdStatus;
import com.tll.mcorpus.db.enums.McuserAuditType;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class McuserAudit implements Serializable {

    private static final long serialVersionUID = 199055541;

    private final UUID            uid;
    private final OffsetDateTime  created;
    private final McuserAuditType type;
    private final OffsetDateTime  requestTimestamp;
    private final String          requestOrigin;
    private final OffsetDateTime  loginExpiration;
    private final UUID            jwtId;
    private final JwtIdStatus     jwtIdStatus;

    public McuserAudit(McuserAudit value) {
        this.uid = value.uid;
        this.created = value.created;
        this.type = value.type;
        this.requestTimestamp = value.requestTimestamp;
        this.requestOrigin = value.requestOrigin;
        this.loginExpiration = value.loginExpiration;
        this.jwtId = value.jwtId;
        this.jwtIdStatus = value.jwtIdStatus;
    }

    public McuserAudit(
        UUID            uid,
        OffsetDateTime  created,
        McuserAuditType type,
        OffsetDateTime  requestTimestamp,
        String          requestOrigin,
        OffsetDateTime  loginExpiration,
        UUID            jwtId,
        JwtIdStatus     jwtIdStatus
    ) {
        this.uid = uid;
        this.created = created;
        this.type = type;
        this.requestTimestamp = requestTimestamp;
        this.requestOrigin = requestOrigin;
        this.loginExpiration = loginExpiration;
        this.jwtId = jwtId;
        this.jwtIdStatus = jwtIdStatus;
    }

    public UUID getUid() {
        return this.uid;
    }

    public OffsetDateTime getCreated() {
        return this.created;
    }

    public McuserAuditType getType() {
        return this.type;
    }

    public OffsetDateTime getRequestTimestamp() {
        return this.requestTimestamp;
    }

    public String getRequestOrigin() {
        return this.requestOrigin;
    }

    public OffsetDateTime getLoginExpiration() {
        return this.loginExpiration;
    }

    public UUID getJwtId() {
        return this.jwtId;
    }

    public JwtIdStatus getJwtIdStatus() {
        return this.jwtIdStatus;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("McuserAudit (");

        sb.append(uid);
        sb.append(", ").append(created);
        sb.append(", ").append(type);
        sb.append(", ").append(requestTimestamp);
        sb.append(", ").append(requestOrigin);
        sb.append(", ").append(loginExpiration);
        sb.append(", ").append(jwtId);
        sb.append(", ").append(jwtIdStatus);

        sb.append(")");
        return sb.toString();
    }
}
