/*
 * This file is generated by jOOQ.
*/
package com.tll.mcorpus.db.tables.pojos;


import com.tll.mcorpus.db.enums.JwtIdStatus;
import com.tll.mcorpus.db.enums.McuserAuditType;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class McuserAudit implements Serializable {

    private static final long serialVersionUID = -85464092;

    private final UUID            uid;
    private final Timestamp       created;
    private final McuserAuditType type;
    private final Timestamp       requestTimestamp;
    private final String          requestOrigin;
    private final Timestamp       loginExpiration;
    private final UUID            jwtId;
    private final JwtIdStatus     jwtIdStatus;

    public McuserAudit(McuserAudit value) {
        this.uid = value.uid;
        this.created = value.created;
        this.type = value.type;
        this.requestTimestamp = value.requestTimestamp;
        this.requestOrigin = value.requestOrigin;
        this.loginExpiration = value.loginExpiration;
        this.jwtId = value.jwtId;
        this.jwtIdStatus = value.jwtIdStatus;
    }

    public McuserAudit(
        UUID            uid,
        Timestamp       created,
        McuserAuditType type,
        Timestamp       requestTimestamp,
        String          requestOrigin,
        Timestamp       loginExpiration,
        UUID            jwtId,
        JwtIdStatus     jwtIdStatus
    ) {
        this.uid = uid;
        this.created = created;
        this.type = type;
        this.requestTimestamp = requestTimestamp;
        this.requestOrigin = requestOrigin;
        this.loginExpiration = loginExpiration;
        this.jwtId = jwtId;
        this.jwtIdStatus = jwtIdStatus;
    }

    public UUID getUid() {
        return this.uid;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public McuserAuditType getType() {
        return this.type;
    }

    public Timestamp getRequestTimestamp() {
        return this.requestTimestamp;
    }

    public String getRequestOrigin() {
        return this.requestOrigin;
    }

    public Timestamp getLoginExpiration() {
        return this.loginExpiration;
    }

    public UUID getJwtId() {
        return this.jwtId;
    }

    public JwtIdStatus getJwtIdStatus() {
        return this.jwtIdStatus;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("McuserAudit (");

        sb.append(uid);
        sb.append(", ").append(created);
        sb.append(", ").append(type);
        sb.append(", ").append(requestTimestamp);
        sb.append(", ").append(requestOrigin);
        sb.append(", ").append(loginExpiration);
        sb.append(", ").append(jwtId);
        sb.append(", ").append(jwtIdStatus);

        sb.append(")");
        return sb.toString();
    }
}
